name: Draw ZMK keymap

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/info.json"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      output_folder: "keymap-drawer"
      draw_args: "totem:'-j config/info.json -l LAYOUT'"
